package org.daniels.examples;

global String topicLevel

rule "Drools Introduction"
	when
		$droolsIntro : DroolsIntroduction( topic != null && topic.contains("Drools") )
	then
		System.out.println($droolsIntro.introduceYourself() + ", topic level is " + getDefaultIfNull(topicLevel));
end

function String getDefaultIfNull(String topicLevel) {
	return topicLevel == null ? "Moderate" : topicLevel;
}